### ISSUE TITLE
Module not found issue in NextJS server action

### ISSUE THREAD

**Issue by flogy** [3AP-AG/payrexx-sdk#38]
Hoi zäme / hi there

First of all, thank you for building this helpful library!

I just tried to use it within a NextJS 14 server action. It did not work and threw a `Module not found` exception.

After a little debugging I found that the paths in the `package.json` seem to be incorrect.

PR will follow shortly.

Cheers,
Florian

**Comment by veljko3ap** [comment]
Thank you for using the library and for reporting the issue. 
I'll take a look at the PR 👍🏻

**Comment by flogy** [comment]
@veljko3ap Awesome, thank you for the swift response! 🎉

**Comment by veljko3ap** [comment]
@flogy You can find the latest version with your fixes available on https://www.npmjs.com/package/payrexx-sdk
